### PR TITLE
Saved Profiles for PID/Rate/Filter/Alarm

### PR DESCRIPTION
**Pull request by BigBangPro**
Added Saved Profiles through Menu for PIDs/Rates/Filters & Alarms (5 each).  Code is too large standalone for the radio, but a compiled version works fine in the radio.  Companion 2.2 RC10/12/13 works fine.  Happy for someone to rebuild the code to reduce size and memory usage.

### CODE REVIEW

**Comment by fedorcomander** [comment]
I will merge this after release. I need to reduce code size to bare minimum...

**Comment by BigBangPro** [comment]
no probs - not sure where the code can be scrapped out, but good luck.  did you get the X7 version aswell?

**Comment by fedorcomander** [comment]
X7 works ;)

**Comment by BigBangPro** [comment]
sweet.  started looking at the horus - wow......might need another "Drink" before i start that lol

**Comment by fedorcomander** [comment]
Dare to implement on the common code base now? ;)

**Comment by BigBangPro** [comment]
Have used AWolf's tpa setup and cooked it into mine and works a treat. Even put 5 TPA defaults into it. Need to test then will merge to my PR

**Comment by BigBangPro** [comment]
TEST: read need to cut down code

**Comment by BigBangPro** [comment]
adjusted kissfc.lua for the X9D to have the saved data sets menu

**Comment by BigBangPro** [comment]
X7 done.  Horus to go

**Comment by awolf78** [comment]
@BigBangPro 
You want to do your PR first?
I can pull my PR afterwards (and integrate your profiles in TPA) - up to you.

Cooking my TPA in your PR: Not cool. Sorry man.

**Comment by BigBangPro** [comment]
TPA - sincere apologies mate, totally new to this PR stuff, lesson learned.  
You can go first @awolf78, I'm leaving for 3 week holiday today with no computers 🤔😎 so don't wait for me.

**Comment by BigBangPro** [comment]
@fedorcomander, happy for you to close this PR, will start a new one when i get back. Cheers

**Comment by awolf78** [comment]
@BigBangPro It's all good ;)
Enjoy your holidays!

**Comment by BigBangPro** [comment]
@awolf78  thanks mate, got a little too excited and jumped the gun on TPA. Have a working copy i am taking away with me to fly with, so good times ahead - allows me to leave the laptop behind😉

**Pull request closed without merging**
