### PR TITLE
Horus LUA Support

### PR DESCRIPTION
**Pull request by lichtl**
Hi, still some WIP but thought to raise the PR so others could start testing (PID and Rate pages should work)

Due to lack of Hardware I'm unable to test it atm.

### CODE REVIEW

**Comment by fedorcomander** [comment]
I will hold it for a bit, we are busy with preparing release. Will merge it after that if you dont mind.

**Comment by lichtl** [comment]
No worries. As mentioned I still need to fix some pages. Will update the PR subject once completed

**Comment by fedorcomander** [comment]
while you at it.change make to be 6 symbols + .lua

**Comment by lichtl** [comment]
ok pages seem fine on the simulator. As mentioned I'm unable to test this at the moment so anyone having a Horus and latest firmware would be great to confirm that this is working.

**Pull request closed without merging**
